### ISSUE TITLE
Any plans on making something resembling React's JSX?

### ISSUE THREAD

**Issue by wle8300** [guisouza/tembo#4]

**Comment by guisouza** [comment]
JSX is not part of the lib itself, its more like a building process, but it would be nice =D.
I will keep it open for now.

**Comment by wle8300** [comment]
Oh yea that's right.

I think something comparable to JSX is non-negotiable. It just makes visualizing the markup much easier in your head.

**Comment by alanrsoares** [comment]
It's quite straight forward to have it working once you make sure the `createElement` method follows the same signature as React's one. The only required config step then will be the `jsxPragma` option in `.babelrc`

**Comment by guisouza** [comment]
@alanrsoares thats right ! .. 
buuuut .. i am planning to add an external template load in html format or passing it in the string format
like in angularJS for example .. 
JSX isn't necessary . and like you said  this can already be done in today implementation.

@alanrsoares  tks for your :watch:  and attention!  :heart: :octocat: !

:facepunch: :facepunch: :facepunch:

**Comment by guisouza** [comment]
@williamle8300 If you want, feel free send a PR expaining the @alanrsoares suggested implementation in the read-me . it would be AWESOME :rainbow: 

@williamle8300  tks for your :watch:  and attention!  :heart: :octocat: !

:facepunch:  :facepunch:  :facepunch:

**Comment by guisouza** [comment]
@alanrsoares solution detailed here : https://medium.com/@claudiopro/use-babel-to-compile-jsx-to-virtual-dom-other-than-react-1cd2d6526609

**Comment by alanrsoares** [comment]
@guisouza, yup, that's it.

babel is tricked by something like this

``` javascript

import { createElement } from 'tembo'

const React = { createElement }
```

[live example](http://jsbin.com/torela/edit?js,output)
