### ISSUE TITLE
Major Refactor If you're interested

### ISSUE THREAD

**Issue by formula1** [guisouza/tembo#7]
https://github.com/formula1/tEmbO/tree/compare

So, I saw what you were doing but I wasn't entirely sure why. Regardless, I make the file structure more class based. I made alot of changes and tried to reuse your code whenever possible.
- [interface](https://github.com/formula1/tEmbO/tree/compare/src/interface) - You have Patch and Component, both of which are abstract classes the client interacts with but are not technically anything of large interest.
- [render](https://github.com/formula1/tEmbO/tree/compare/src/render) - This is where I made much bigger changes. 
  - NativeRoot - So I have something called a NativeRoot which acts as the branches to the component tree. Even when the branch exists, the component may still return null within the render. As a result we need to keep track of what the actual value is in addition to how it is being rendered. 
  - ShadowNode - The second part is ShadowNode. So I create a component that returns a component when it renders. This keeps happening until we hit a native structure. I realized that the Component is actually the exact same entity as that it renders, all the way down. However
- [updaters](https://github.com/formula1/tEmbO/blob/compare/src/Tembo.js) - The last part that's important is the updaters. Theres a few update strategies I'm particularly interested in. First is batching where all updates being done are done at the same time. This actually is pretty slow despite me thinking it solved some sort of problem. Then second it promised based which I think is somewhat interesting. Basiclally the idea is that children will wait for parents to finish but we can alllow siblings and more distant relatives to render in parallel. I created this concept because I'm particularly interested to see if I can manage to build a png creator out of it. The one implemented is a mix of both and a terrible one at that. But I think the real problem is that I'm trying to do this at the abstraction level instead of the paint level. Regardless, options are available

I think within this structure it will be far easier to implement hooks like 'willUpdate' and etc. Before I was a bit confused tbh. But then again, I say that subjectively. Which is why I made an issue rather than a PR. I hope you are interested in this because I think tEmbO is the right kind of cute experiment for me.

**Comment by guisouza** [comment]
@formula1 first of all, thank you so much for your :watch:  and attention! :heart: :octocat: 
I really appreciate your effort on this project, I just cant handle my happiness reading your code.
just give me some time so I can really understand every key-stroke of your refactoring, and we merge it.
I am working on a BIG thing and tEmbO will be my rendering engine for it, so I really want to keep track of everything thats going on inside this thing ..  

add me on skype : "guilhermesouza." so I can show you my new project .
Thank you again !

**Comment by formula1** [comment]
Absolutely! I'm probably as excited as you are. Not everyday when you see someone be willing to remake the wheel in their own words. Sent you an email and sent you a message over skype. I'm confident if we do a good enough job it could probably be presented to a convention or something

**Comment by formula1** [comment]
Update: I updated mount and unmount tests and am passing both on my branch. I wanted to do it for master but it was a bit of a pain to be honest. I can pull test updates to master but it simply sets a bar
